config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'users#show', as: 'profile'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about"
  get "test" => "pages#test"
  get "faqs" => "pages#faqs"
  get "howitworks" => "pages#how_it_works", as: :how_it_works
  get "success" => "pages#success", as: :success
  post '/chatbot/chat', to: 'messages#chat'

  # Defines the root path route ("/")
  # root "posts#index"

  resources :companies, only: [:index, :show]
  resources :jobs, only: [:index, :show, :create] do
    resources :saved_jobs, only: [:create]
    collection do
      post :apply_to_selected_jobs, as: :apply
    end
    # TODO: fix app if breaking because you'll now need to specify the job in params
    resources :job_applications, only: [:create]
  end

  resources :job_applications, only: [:index, :show, :new, :success]

  resources :saved_jobs, only: [:index, :show, :destroy]
  resources :educations, only: [:new, :create]

end

app/models/job.rb
class Job < ApplicationRecord
  include Ats::Greenhouse
  include Ats::Workable
  serialize :application_criteria, JSON
  belongs_to :company
  belongs_to :applicant_tracking_system, optional: true
  belongs_to :ats_format, optional: true
  has_many :job_applications, dependent: :destroy
  has_many :saved_jobs, dependent: :destroy
  has_many :playlist_jobs
  has_many :job_playlists, through: :playlist_jobs
  before_create :set_application_criteria

  validates :job_title, presence: true
  # validates :job_posting_url, uniqueness: true

  # TODO: Add validations to job model
  # validates :applicant_tracking_system_id, :ats_format_id, presence: true

  include PgSearch::Model

  pg_search_scope :global_search,
    against: [:job_title, :salary, :job_description],
    associated_against: {
      company: [ :company_name, :company_category ]
    },
    using: {
      tsearch: { prefix: true }
    }

  def set_application_criteria
    if job_posting_url.include?('greenhouse')
      self.application_criteria = Job::GREENHOUSE_FIELDS
    elsif job_posting_url.include?('workable')
      self.application_criteria = Job::WORKABLE_FIELDS
    else
      self.application_criteria = {}
    end
  end

  # Enables access to application_criteria via strings or symbols
  def application_criteria
    read_attribute(:application_criteria).with_indifferent_access
  end
end

# Commented out as not required - converts symbols to strings in the JSONB object
# def application_criteria
#   super.transform_keys(&:to_sym)
# end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true, on: :create

  has_many :job_applications, dependent: :destroy
  has_many :jobs, through: :job_applications
  has_many :saved_jobs, dependent: :destroy
  has_many :educations, dependent: :destroy

  has_one_attached :photo
  has_one_attached :resume
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:query].present?
      @jobs = Job.global_search(params[:query])
      @initial_jobs = Job.global_search(params[:query]).limit(10)
      @remaining_jobs = Job.global_search(params[:query]).offset(10)
    else
      @jobs = Job.all
      @initial_jobs = Job.limit(10)
      @remaining_jobs = Job.offset(10)
    end
    @job = Job.new
    @saved_job = SavedJob.new
    @saved_jobs = SavedJob.all
    @job_applications = JobApplication.where(user_id: current_user.id)
  end

  def show
    @job = Job.find(params[:id])
    @saved_job = SavedJob.new
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to job_path(@job), notice: 'Job was successfully added'
    else
      @jobs = Job.all
      render 'jobs/index', status: :unprocessable_entity
    end
  end

  def apply_to_selected_jobs
    # Fetch the selected job IDs from the parameters


    p "---------------------"
    p "---------------------"
    p "---------------------"
    p "---------------------"
    p "---------------------"
    p "---------------------"
    p "---------------------"

    p "Params:"
    p params
    selected_job_ids = params[:job_ids]
    cookies[:selected_job_ids]
    cookies[:job_app_no] ||= 0


    # Instead of directly creating job applications, store the selected jobs in the session or another temporary store
    cookies[:selected_job_ids] = selected_job_ids
    cookies[:job_app_no] = cookies[:job_app_no].to_i + 1
    # raise
    # Redirect to a new action that will display the staging page
    redirect_to new_job_application_path
  end

  private

  def job_params
    params.require(:job).permit(:job_title, :job_description, :salary, :job_posting_url, :application_deadline, :date_created, :company_id)
  end
end

# def apply_to_selected_jobs
#   selected_job_ids = params[:job_ids]
#   selected_job_ids.each do |job_id|
#     job_app = JobApplication.create(job_id: job_id, user_id: current_user.id, status: "Pre-application")
#     ApplyJob.perform_now(job_app.id, current_user.id)
#     # flash[:notice] = "You applied to #{Job.find(job_id).job_title}!"
#   end
#   redirect_to job_applications_path
# end

app/views/jobs/_form.html.erb
  <div class="container vh-180 d-flex align-items-center justify-content-center">
    <div class="d-flex justify-content-center align-items-center w-50 border shadow rounded p-2 m-4 d-none" data-new-job-form-target="form">
      <div class="col-md-10 p-0 m-0"> <!-- Adjust the column size as needed -->
        <div class="form-box text-center">
                <%= simple_form_for [@job] do |f| %>
                <%= f.association :company, collection: Company.all, :label_method => lambda { |company| "#{company.company_name}"}, prompt: "Choose a company", label_html: { style: 'font-style: italic;' } %>
                <%= f.input :job_title, label_html: { style: 'font-style: italic;' } %>
                <%= f.input :job_description, label_html: { style: 'font-style: italic;' } %>
                <%= f.input :salary, label_html: { style: 'font-style: italic;' } %>
                <%= f.input :job_posting_url, label_html: { style: 'font-style: italic;' } %>
                <%= f.input :application_deadline, label_html: { style: 'font-style: italic;' } %>
                <%= f.input :date_created, label_html: { style: 'font-style: italic;' } %>
                <%= f.submit 'Add this job', class: 'btn-add-info'%>
              <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/jobs/_row.html.erb
<div class="row mb-3"  data-select-by-job-type-target="jobRow" data-styling-selected-job-target="jobCard">
  <div class="col-12">
    <div class="card job-card">
      <div class="card-body">
        <div class="row text-center">
          <div class="col card-logo companyname" data-name="<%= job.company.company_name %>"><%= image_tag("https://logo.clearbit.com/#{job.company.company_website_url}?size=60", onerror: "this.src='https://i.pinimg.com/736x/ec/d9/c2/ecd9c2e8ed0dbbc96ac472a965e4afda.jpg'") %><p class="d-none"><%= job.company.company_name%></p></div>
          <div class="col-2 role pe-2 " data-role="<%= job.job_title %>"><%= job.job_title.truncate(50) %></div>
          <div class="col-2 d-none job-description-small" data-job-index-toggle-target="newColumn2"><%= job.job_description.truncate(90) %></div>
          <div class="col salaryBudget"><%= job.salary ? "£#{number_with_delimiter(job.salary, delimiter: ',')}" : "n/a" %></div>
          <div class="col">
            <% if (Time.now.next_day(7)) >= job.application_deadline %>
              <button class="btn btn-closing-soon">CLOSING SOON</button>
            <% elsif Time.now < job.application_deadline %>
              <button class="btn btn-status">OPEN</button>
            <% else %>
              <button class="btn btn-closed">CLOSED</button>
            <% end %>
          </div>
          <div class="col"><%= job.application_deadline.strftime("%d/%m") %></div>
          <div class="col d-none">
            <% if job.application_criteria.instance_of?(Hash) && job.application_criteria["resume"].any? %>
              YES
            <% else %>
              NO
            <% end %>
          </div>
          <div class="col">
            <%= link_to job.job_posting_url, target: "_blank" do %>
              <i class="fa-solid fa-external-link-alt"></i>
            <% end %>
          </div>
          <div class="col ">
            <% if SavedJob.where(job_id: job.id).present? %>

              <%= link_to saved_job_path(job.saved_job_ids), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this job from your list?"} do %>
                <i class="fa-solid fa-heart saved-job-heart-icon"></i>
              <% end %>
            <% else %>
              <%= link_to job_saved_jobs_path(job), data: {turbo_method: :post} do %>
                <i class="fa-regular fa-heart not-saved-job-heart-icon"></i>
              <% end %>
            <% end %>
          </div>

          <% if JobApplication.where(job_id: job.id, user_id: current_user.id).present? %>
            <div class="col already-applied-tick">
              <i class="fa-solid fa-check"></i>
            </div>
          <% else %>
            <div class="col selectBox">
              <label class="custom-checkbox" data-job-index-toggle-target="jobCheckbox" data-action="click->job-index-toggle#updateApplyButton">
                <%= check_box_tag "job_ids[]", job.id, id: "job_id", class: 'select-job-box', data: { styling_selected_job_target: "checkBox", action: 'change->styling-selected-job#styleCard' } %>
                <span class="checkmark"></span>
              </label>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_search.html.erb
<div id="jobs-search-bar" class="search-bar-background">
  <%= form_tag jobs_path, method: :get, class: 'd-flex' do %>
    <%= text_field_tag :query,
        params[:query],
        class: 'form-control',
        placeholder: 'Search for any job, company or role... ', style: 'font-style: italic;', id: 'search-jobs' %>

    <%= link_to jobs_path, class: 'clear-search-icon' do %>
      <i class="fa-solid fa-x"></i>
    <% end %>

    <%= submit_tag 'Search', id: 'search-button' %>
  <% end %>



</div>

app/views/jobs/index.html.erb
<div class="container" data-controller="select-by-job-type styling-selected-job">
  <div class="search-container d-flex justify-content-center align-items-center">
    <%= render 'search' %>
  </div>
    <div class="row" data-controller="job-index-toggle">

      <%# LHS Section Divider %>
      <div class="col-sm-3" id="jobs-index-left-section" data-job-index-toggle-target="leftSection">

        <%# LHS Section - Title and Search  %>
        <div class="d-flex justify-content-between">
          <h6 id="jobs-index-left-section-title">
            <% if params[:query].present? %>
              <%= @jobs.count %>
            <% else %>
              <%= @jobs.count - @job_applications.count %>
            <% end %>
            Jobs
          </h6>
        </div>

        <%# TODO: Add icons %>
        <h5 class="mt-4 mb-3", style="color: #6007C6;"><i class="fa-solid fa-building-user"></i> Companies</h5>
        <ul id="companies-select">
          <div>
            <% Company.all.each do |company| %>
              <% if Job.where(company: company).any? %>
                <div class="companies-select-item">
                  <label for="<%= company.company_name %>" class="companies-select-item-label">
                  <input class="companies-select-item-checkbox" type="checkbox" name="<%= company.company_name %>" id="<%= company.company_name %>" <%= params[:company] && params[:company].downcase.include?(company.company_name.downcase) ? "checked" : "" %> data-action="change->select-by-job-type#combinedSearch" data-select-by-job-type-target="company">
                  <%= company.company_name %>
                  </label><br>
                </div>
              <% end %>
            <% end %>
          </div>
        </ul>

        <%# TODO: Add icons %>
        <%# LHS Section - Search by Job Type %>
        <h5 class="mt-4 mb-3", style="color: #6007C6;"><i class="fa-solid fa-person-chalkboard"></i> Job Roles</h5>
        <ul id="job-types-select">
          <div class="job-types-select-item">

            <label for="Full Stack" class="job-types-select-item-label">
            <input class="job-types-select-item-checkbox" type="checkbox" name="Full Stack" id="full stack" data-action="change->select-by-job-type#combinedSearch" data-select-by-job-type-target="role">
            Full Stack
            </label>

            <label for="Back End" class="job-types-select-item-label">
            <input class="job-types-select-item-checkbox" type="checkbox" name="Back End" id="back end" data-action="change->select-by-job-type#combinedSearch" data-select-by-job-type-target="role">
            Back End
            </label>

            <label for="Front End" class="job-types-select-item-label">
            <input class="job-types-select-item-checkbox" type="checkbox" name="Front End" id="front end" data-action="change->select-by-job-type#combinedSearch" data-select-by-job-type-target="role">
            Front End
            </label>

          </div>
        </ul>

      </div>

      <%# RHS Section Divider %>
      <div class="col-sm-9 p-0" id="jobs-index-right-section" data-job-index-toggle-target="rightSection">
        <%= form_tag apply_jobs_path, method: :post do %>
          <div class="sticky-top bg-white">
            <div class="d-flex justify-content-between align-items-center pt-1">
              <div class="d-flex align-items-center cursor-pointer" data-action="click->job-index-toggle#toggleView" data-job-index-toggle-target="toggleButton1">
                <i class="fa-solid fa-circle-left"></i>
                <p class="my-0 ms-1">Hide Categories</p>
              </div>
              <div class="d-flex align-items-center d-none cursor-pointer" data-action="click->job-index-toggle#toggleView" data-job-index-toggle-target="toggleButton2">
                <i class="fa-solid fa-circle-right"></i>
                <p class="my-0 ms-1">Show Categories</p>
              </div>
              <div>
                <%= submit_tag "Apply to 0 Jobs", id: "apply-button", "data": {job_index_toggle_target: "applyButton"}, class: "btn btn-apply" %>
              </div>
            </div>

            <%# RHS Section - Job Table Headers %>
            <div class="row">
              <div class="col-12">
                <div class="card job-list-header">
                  <div class="card-body">
                    <div class="row text-center">
                      <div class="col">Company</div>
                      <div class="col-2">Role</div>
                      <div class="col-2 d-none" data-job-index-toggle-target="newColumn1">Description</div>
                      <div class="col">Salary</div>
                      <div class="col">Status</div>
                      <div class="col">Deadline</div>
                      <div class="col">Details</div>
                      <div class="col">Save</div>
                      <div class="col">Select</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <%# RHS Section - Job Table %>
          <div class="job-cards-container pt-0" data-controller="load-more">
            <% @initial_jobs.each do |job| %>
              <% if JobApplication.where(job_id: job.id, user_id: current_user.id).blank? %>
                <%= render 'row', job: job %>
              <% end %>
            <% end %>
            <div data-load-more-target="remaining" class="d-none">
              <% @remaining_jobs.each do |job| %>
                <%= render 'row', job: job %>
              <% end %>
            </div>
            <div class="d-flex justify-content-start">
              <%= link_to "Show More", "#", data: { action: "click->load-more#showMore" }, class: "btn btn-apply", "data-load-more-target": "button" %>
            </div>
          </div>
        <% end %>

      <div data-controller="new-job-form">
        <button id="btn-add-job" class="d-none" data-action="click->new-job-form#displayForm" data-new-job-form-target="button">Add a Job</button>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="job-show-title">
    <h3><%= @job.job_title %></h3>
    <%= link_to 'Apply to this job', job_job_applications_path(@job), data: {turbo_method: :post}, class: "btn-apply" %>
    <div class="icon-save-job">
      <%= simple_form_for [@job, @saved_job] do |f| %>
        <%= button_tag type: 'submit' do %>
          <i class="fa-regular fa-heart"></i>
        <% end %>
      <% end %>
    </div>
  </div>

  <p>Company: <%= @job.company.company_name %></p>
  <p>Job title: <%= @job.job_title %></p>
  <p>Job description: <%= @job.job_description %></p>
  <p>Salary: £<%= number_with_delimiter(@job.salary, :delimiter => ',') %></p>

</div>