config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'users#show', as: 'profile'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about"
  get "test" => "pages#test"
  get "faqs" => "pages#faqs"
  get "howitworks" => "pages#how_it_works", as: :how_it_works
  get "success" => "pages#success", as: :success
  post '/chatbot/chat', to: 'messages#chat'

  # Defines the root path route ("/")
  # root "posts#index"

  resources :companies, only: [:index, :show]
  resources :jobs, only: [:index, :show, :create] do
    resources :saved_jobs, only: [:create]
    collection do
      post :apply_to_selected_jobs, as: :apply
    end
    # TODO: fix app if breaking because you'll now need to specify the job in params
    resources :job_applications, only: [:create]
  end

  resources :job_applications, only: [:index, :show, :new, :success]

  resources :saved_jobs, only: [:index, :show, :destroy]
  resources :educations, only: [:new, :create]

end

app/models/job_application.rb
class JobApplication < ApplicationRecord

  # -----------------------------
  # Core Application Criteria:
  # -----------------------------

  CORE_APPLICATION_CRITERIA = {
    first_name: {
      interaction: :input,
    },
    last_name: {
      interaction: :input,
    },
    email: {
      interaction: :input,
    },
    phone_number: {
      interaction: :input,
    },
    resume: {
      interaction: :upload,
    },
    # city: {
    #   interaction: :input,
    # },
    # location_click: {
    #   interaction: :listbox,
    # },
    # linkedin_profile: {
    #   interaction: :input,
    # },
    # personal_website: {
    #   interaction: :input,
    # },
    # heard_from: {
    #   interaction: :input,
    # },
    # # right_to_work: {
    # #   interaction: :select,
    # # },
    # require_visa?: {
    #   interaction: :select,
    # },
  }

  belongs_to :user
  belongs_to :job
  has_many :application_responses, dependent: :destroy

  accepts_nested_attributes_for :application_responses

  has_one_attached :screenshot

  # TODO: Add validations for the job application model
  # TODO: have a complete message taken from the application page on successful execution
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  def index
    @job_applications = JobApplication.all.where(user_id: current_user.id)
  end

  def show
  end

  def new
    # Retrieve the selected job IDs from the session
    @selected_jobs = Job.find(cookies[:selected_job_ids].split("&"))

    @job_applications = @selected_jobs.map do |job|
      job_application = JobApplication.new(user: current_user, status: "Pre-application")

      job.application_criteria.each do |field, details|
        application_response = job_application.application_responses.build
        application_response.field_name = field
        application_response.field_locator = details["locators"]
        application_response.interaction = details["interaction"]
        application_response.field_option = details["option"]
        # TODO: Check with TA if this is the correct approach
        # if field == "resume" && current_user.resume.attached?
        # application_response.field_value = rails_service_blob_proxy_url(current_user.resume, only_path: true)
        # else
        application_response.field_value = current_user.try(field) || ""
        # end
      end

      [job, job_application]
    end
    # raise
    # Renders the staging page where the user can review and confirm applications
  end

  # TODO: Split out core application criteria that is common to all job applications
  # TODO: Split out additional application criteria that is specific to the job
  # TODO: only be able to make a job application if you haven't already applied to the job

  def create
    # Retrieve user inputs from the form

    # user_input = params[:user_input]

    # Process each selected job

    if cookies[:job_app_no].to_i > 1
      job = Job.find(cookies[:selected_job_ids].split("&").first)
    else
      job = Job.find(params[:job_id])
    end

    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p "&&&&&&&&&&&&&&&&&&&&&&&&"
    p job

    # job = Job.find(params[:job_id])

    # update the job/ application criteria

    # Create a job application with the user's input
    @job_application = JobApplication.new(job_application_params)
    @job_application.user = current_user
    @job_application.job = job
    @job_application.status = "Application pending"

    # find out what issue is and if there is one, create or append the validation errors and render new
    p @job_application
    if @job_application.save
      # Perform the job application process
      p "sending job to Applyjob: #{@job_application.id}"
      ApplyJob.perform_later(@job_application.id, current_user.id)
      @job_application.update(status: "Applied")

      # Optional: Add a notification for each application
      # flash[:notice] = "You applied to #{Job.find(job_id).job_title}!"

      # Remove the submitted job IDs from the session
      # raise
      ids = cookies[:selected_job_ids].split("&")
      p ids
      ids.delete("#{job.id}")
      p ids
      cookies[:selected_job_ids] = ids.join("&")

      # Redirect to the job applications index page or another appropriate page
      redirect_to job_applications_path, notice: 'Your applications have been submitted.'
    else
      render :new
    end

    # @job_application = JobApplication.new(job: job, user_id: current_user.id, status: "Pre-application")

  end

  def success
  end

  private

  # TODO: Update job_application_params to include the user inputs

  def job_application_params
    params.require(:job_application).permit(application_responses_attributes: [:field_name, :field_value, :field_locator, :interaction, :field_option])
  end
end


# -----------------------------
# Old Create Method with one job application at a time:
# -----------------------------

# def create
#   # TODO: add failed status to job applications if incomplete - what is the output from the job application page?

#   @job_application = JobApplication.new(status: "Pending")
#   @job = Job.find(params[:job_id])
#   @job_application.job = @job
#   @job_application.user = current_user

#   if @job_application.save
#     if ApplyJob.perform_now(@job_application.id, current_user.id)
#       @job_application.update(status: "Applied")
#       # flash[:notice] = "You applied to #{Job.find(@job_application.id).job.job_title}!"
#       # CHECK IF THIS WORKS
#     end
#     puts "I'm starting the application job"
#     redirect_to job_applications_path, notice: 'Your job application was successful!'
#   else
#     redirect_to job_path(@job), alert: 'Something went wrong, please try again.'
#   end
# end

# -----------------------------
# Old New Method that partially worked
# -----------------------------


# def new
#   # Retrieve the selected job IDs from the session
#   @selected_jobs = Job.find(session[:selected_job_ids])

#   @job_application = JobApplication.new
#   @job_application.user = current_user
#   @job_application.status = "Pre-application"

#   # TODO: Fill application response based on the job application criteria, which is listed as a JSON in the field application_criteria on the job model
#   # TODO: Pull the user input values from the user model
#   # TODO: Add the user input values to the application response

#   @selected_jobs.each do |job|
#     application_response = ApplicationResponse.new
#     job.application_criteria.each do |field, type|
#       application_response[field] = current_user.send(field)
#     end
#     job.application_response = application_response
#   end

#   # We have the selected jobs, we want to render a separate form for each job
#   # Renders the staging page where the user can review and confirm applications
# end

app/views/job_applications/index.html.erb
<div class="container">
  <h3 class="my-applications">My Applications</h3>
  <% @job_applications.each do |application| %>
    <div class='application-wrapper' data-controller="reveal-myapplication-details">
      <div class="application-main-info">
        <button class="toggle-reveal-application-details" data-reveal-myapplication-details-target="toggleReveal" data-action="click->reveal-myapplication-details#revealApplicationDetails">
          <i class="fa-solid fa-caret-right"></i>
        </button>
        <h5 class="m-0"><%= application.job.job_title %> @
        <%= application.job.company.company_name %> </h5> -
        <%= application.status %>
      </div>

      <div id="<%= application.id %>" class="application-secondary-info" data-reveal-myapplication-details-target="applicationDetails">

        <div class="application-secondary-info-left">
          <p><%= application.job.job_description %></p>
          <div>
            <span class="meta-info">Applications Close: <%= application.job.application_deadline.strftime('%d %B %Y') %> - </span>
            <span class="meta-info">Date Applied: <%= application.updated_at.strftime('%d %B %Y') %></span>
          </div>
          <hr class="d-none">
        </div>
        <div class="my-applications-screenshot">
          <% if application.screenshot.attached? %>
            <div class="image-overlay">
              <%= image_tag(cl_image_path application.screenshot.key) %>
            </div>
          <% else %>
            <%= image_tag("job_app_complete_default.jpg") %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/job_applications/new.html.erb
<%= provide(:title, 'New Job Applications') %>

<div class="container mt-5 col-sm-6" data-controller="all-application-forms">
  <div class="d-flex justify-content-between align-items-center ">
      <div class="companies d-flex flex-column justify-content-start mb-4">
        <%# Dynamically load the company logos based on selected jobs %>
        <p class="mb-1">Current applications:</p>

        <div class="company-apply-summary bg-body-secondary p-2 d-flex">
          <%# TODO: Update company logos once pulling from TrueUp (clearbit) %>
          <% @selected_jobs.each_with_index do |job, index| %>
            <div><%= index + 1 %></div>
              <%= link_to image_tag("https://logo.clearbit.com/#{job.company.company_website_url}?size=60", onerror: "this.src='https://i.pinimg.com/736x/ec/d9/c2/ecd9c2e8ed0dbbc96ac472a965e4afda.jpg'", class: 'img-fluid'), '#', class: 'apply-company-logo mr-3' %>
          <% end %>
        </div>
      </div>
      <div class="d-flex justify-content-end align-items-center">
        <div class="btn btn-apply mt-1" data-all-application-forms-target="button" data-action="click->all-application-forms#submitAllForms">Apply All</div>
      </div>
  </div>

  <%# Iterate over each selected job %>
  <div class="all-application-forms m-auto" data-controller=" response-input">
    <% @job_applications.each_with_index do |job, index| %>
      <details class="application-form bg-body-secondary mb-3" open>
        <summary class="pb-1" style="display: block"><h2><%= index + 1 %>. <%= job.first.job_title %></h2></summary>
        <%= simple_form_for job, html: { class: 'needs-validation', 'data-controller': 'application-form', 'data-application-form-target': 'form', 'data-action': 'submit->application-form#submitForm', 'data-all-application-forms-target': "form",  novalidate: true } do |f| %>

          <%# Dynamically create form elements based on application_criteria %>
          <%# Convert to simple_fields_for application_responses. Then use those to create the input fields below. %>
          <% job.last.application_responses.each_with_index do |response, response_index| %>

            <% if response_index == 0 %>
              <details class="core-details bg-light" open>
              <summary class="mb-2 bolded">Core details:</summary>
            <% end %>

            <%= f.simple_fields_for "application_responses", response do |ff| %>
              <div class="form-group row mb-3">
                <label  class="apply-label col-sm-3 col-form-label text-center rounded-pill" for=""><%= response.field_name.humanize %></label>
                <% case ff.object.interaction %>
                <% when "input" %>
                  <div class="col-sm-9 mr-2">
                    <%= ff.input :field_name, as: :hidden, input_html: { class: 'mb-0', style: "margin-bottom: 0px;"}, wrapper_html: { class: 'wrapper-mb-0' }, label: false %>
                    <%= ff.input :field_locator, as: :hidden, input_html: { class: 'mb-0' }, wrapper_html: { class: 'wrapper-mb-0' }, label: false %>
                    <%= ff.input :interaction, as: :hidden, input_html: { class: 'mb-0' }, wrapper_html: { class: 'wrapper-mb-0' }, label: false %>
                    <%= ff.input :field_option, as: :hidden, input_html: { class: 'mb-0' }, wrapper_html: { class: 'wrapper-mb-0' }, label: false %>
                    <%= ff.input :field_value , label: false, wrapper_html: { class: 'wrapper-mb-0' }, input_html: { class: "rounded-pill", data: { label: response.field_name, response_input_target: "input", action: "keyup->response-input#handleChange change->response-input#handleChange"} } %>
                  </div>
                <% when "upload" %>
                  <div class="col-sm-9 mr-2">
                    <%= ff.input :field_name, as: :hidden, wrapper_html: { class: 'wrapper-mb-0' } %>
                    <%= ff.input :field_locator, as: :hidden, wrapper_html: { class: 'wrapper-mb-0' } %>
                    <%= ff.input :interaction, as: :hidden, wrapper_html: { class: 'wrapper-mb-0' } %>
                    <%= ff.input :field_option, as: :hidden, wrapper_html: { class: 'wrapper-mb-0' } %>
                    <%= ff.input :field_value, label_html: { class: "d-none"}, input_html: { class: "rounded-pill", data: { label: response.field_name, response_input_target: "input", action: "keyup->response-input#handleChange change->response-input#handleChange"}, value: current_user.resume.attached? ? current_user.resume.filename : nil }, wrapper_html: { class: 'wrapper-mb-0' } %>
                  </div>
                <% when "combobox" %>
                  <div class="col-sm-9">
                    <%= ff.input :field_name, as: :hidden %>
                    <%= ff.input :field_locator, as: :hidden %>
                    <%= ff.input :interaction, as: :hidden %>
                    <%= ff.input :field_option, as: :hidden %>
                      <p>TODO: Add a COmbobox handler. Value is combobox field_option.</p>

                    <%= ff.input :field_value, label: false, wrapper_html: { class: 'wrapper-mb-0' }, input_html: { class: "rounded-pill", data: { label: response.field_name, response_input_target: "input", action: "keyup->response-input#handleChange change->response-input#handleChange"} } %>
                  </div>
                <% end %>

              </div>
            <% end %>

            <% if response.field_name == "resume" %> <%# This is the last CORE APPLICATION FIELD%>
              </details>
              <details class="core-details bg-light" open> <%# Add a new details tag for additional details %>
                <summary class="mb-2 bolded">Additional details:</summary> <%# Close the additional details tag %>
            <% end %>
            <% if response_index + 1 == job.last.application_responses.length %>
              </details>
            <% end %>
          <% end %>
          <%# TODO: Map data types here.s %>
          <%# TODO: Handle File uploads %>


          <div class="d-flex justify-content-end align-items-end">
            <%= f.submit 'Submit this application', class: 'btn btn-apply', 'data-action': 'click->application-form#submitForm' %>
          </div>
        <% end %>
        </details>
    <% end %>
  </div>
</div>

<%# job.last.application_responses[4].field_name %>

app/views/job_applications/show.html.erb
<div class="confirmation-container mt-3" data-controller="confetti">
  <div class="success-box">
    <div class="confirmation-header">
        <h1>🎉 Well done 🎉</h1>
        <% @job_applications = JobApplication.all %>
        <% apps_submitted = @job_applications.where(user_id: current_user.id).all.count %>
        <% hours_saved = (apps_submitted * 0.2).ceil %>
        <h4>You've now applied to <strong><%= apps_submitted %> jobs</strong> with Cheddar... saving <strong>~<%= hours_saved %></strong> <%= hours_saved == 1 ? "hour" : "hours" %> of your time</h4>
        <% dog_names = ["Biscuit", "Cookie", "Muffin", "Brownie", "Cupcake", "Pretzel", "Waffle", "Pancake", "Donut"] %>
        <h4 class="pt-3"><%= dog_names.sample.capitalize %> is proud of you</h4>
    </div>
    <div class="confirmation-body mt-0 pb-3 d-flex align-items-center" data-action="click->confetti#click" style="cursor:pointer; max-height: 400px; overflow: hidden; border-radius: 10px; object-fit: cover;">
        <%= link_to image_tag('https://source.unsplash.com/random/900%C3%97700/?dog', alt: 'Happy dog unsplash', class: 'confirmation-body-img') %>
    </div>
    <div class="confirmation-actions pb-2">
      <h5 class="pt-2">Next steps</h5>
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <%= link_to 'Apply again', new_job_application_path, class: "btn btn-apply" %>
        </div>
        <button id="confetti-btn" data-action="click->confetti#click" class="btn btn-cheddar-secondary">More confetti!</button>
        <div>
          <%= link_to 'Tell a friend', '#', class: "btn btn-apply" %>
        </div>
      </div>
      <div class="d-flex justify-content-between align-items-center" style="width: auto;">
        <div class="mx-auto" style="text-align: left; width: 350px;">
          <p class="text-left">1. Check your inbox for confirmation emails</p>
          <p class="text-left">2. Apply to more jobs</p>
          <p class="text-left">3. Tell a friend about Cheddar</p>
        </div>
      </div>
    </div>
  </div>
</div>