config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'users#show', as: 'profile'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about"
  get "test" => "pages#test"
  get "faqs" => "pages#faqs"
  get "howitworks" => "pages#how_it_works", as: :how_it_works
  get "success" => "pages#success", as: :success
  post '/chatbot/chat', to: 'messages#chat'

  # Defines the root path route ("/")
  # root "posts#index"

  resources :companies, only: [:index, :show]
  resources :jobs, only: [:index, :show, :create] do
    resources :saved_jobs, only: [:create]
    collection do
      post :apply_to_selected_jobs, as: :apply
    end
    # TODO: fix app if breaking because you'll now need to specify the job in params
    resources :job_applications, only: [:create]
  end

  resources :job_applications, only: [:index, :show, :new, :success]

  resources :saved_jobs, only: [:index, :show, :destroy]
  resources :educations, only: [:new, :create]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <div class="d-flex justify-content-start">
    <%= link_to "/#", class: "navbar-brand" do %>
      <%= image_tag("cheddar_logo_icon.svg", alt: "Logo") %>
    <% end %>
      <%= image_tag("cheddar_logo_text.svg", alt: "logo", class: "larger-image mt-3") %>
  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# TODO: Fix spacing on elements when hovered %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-flex flex-row align-items-center">
        <li class="pe-4 rounded-pill">
          <div class="btn btn-light rounded-pill">Demo Mode</div>
        </li>
        <li class="nav-item active">
          <%= link_to "How It Works", how_it_works_path, class: "nav-link d-none" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Find Jobs", jobs_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item active d-none">
            <%= link_to "Find Jobs", jobs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Dashboard", profile_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Apps", job_applications_path, class: "nav-link d-none" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, class: "avatar" %>
              <% else %>
                <%= image_tag "avatar_default.png", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Applications", job_applications_path, class: "dropdown-item" %>
              <%= link_to "My Saved Jobs", saved_jobs_path, class: "dropdown-item" %>
              <%= link_to "My Profile", profile_path(current_user), class: "dropdown-item d-none" %>
              <%= link_to "Job Preferences", profile_path(current_user), class: "dropdown-item d-none" %>
              <%= link_to "Settings", profile_path(current_user), class: "dropdown-item d-none" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>